// Single source of truth for SEO metadata, sitemap, robots and structured data.
// Set NEXT_PUBLIC_SITE_URL once a custom domain is live (no trailing slash).
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://corenextproject.vercel.app').replace(/\/$/, '')

export const SITE = {
  name: 'CoreNext Project',
  shortName: 'CoreNext',
  title: 'Final Year Projects & Journal Publishing in Chennai | CoreNext',
  description:
    'Final year projects with source code, Scopus/IEEE journal publishing and Arduino/IoT hardware projects in Chennai. AI/ML, Web, Cloud & more. Call +91 9360056977.',
  phone: '+91-9360056977',
  email: 'techcorenext@gmail.com',
  address: {
    streetAddress: 'Sri Balaji Nagar',
    addressLocality: 'Chennai',
    addressRegion: 'Tamil Nadu',
    postalCode: '600077',
    addressCountry: 'IN',
  },
  themeColor: '#030712',
  // Add real profile URLs here (Instagram, LinkedIn, YouTube...) — used for schema sameAs.
  socials: [] as string[],
  googleVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
}

// Generated by app/opengraph-image.tsx. Pages that override `openGraph` must pass this
// explicitly, otherwise the inherited preview image is dropped.
export const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'CoreNext Project – Final Year Projects, Journal Publishing & Hardware Projects in Chennai',
}
